B2C/urls.py
from django.urls import path

from .views import index, order
from .func import newcheck

app_name = 'B2C'

urlpatterns = [
    #인덱스
    path('', index.main, name='index'),

    #주문
    path('order/index', order.order_index, name='order'),
    path('order/orderlist/', order.List_view, name='orderlist'),
    path('order/orderlistEn/', order.orderlistEn, name='orderlistEn'),  # 체크 필요
    path('order/orderlistJeju/', order.orderlistJeju, name='orderlistJeju'),
    path('order/orderlistSauce/', order.orderlistSauce, name='orderlistSauce'),

    path('api/getsabangorder/', order.Update_order, name='getorder'),

    path('orderlistmodal/', order.orderlistmodal, name='orderlistmodal'),
    ## new check 설정
    path('newcheck/set_product/', newcheck.new_set_product, name='newcheck'),
    path('orderlistmodal/', order.orderlistmodal, name='orderlistmodal'),

    path('workorder/', order.work_order, name='workorder'),
    path('release/', order.release_list, name='release'),
    path('workorder/', order.work_order, name='workorder'),

    path('salesreport/', order.salesreport, name='salesreport')

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="{{ descript }}"/>

    <title>은하수산 SCM</title>
    <link rel="shortcut icon" href="{% static 'img/topLogo.ico' %}"/>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    <link href="{% static 'css/menu.css' %}" rel="stylesheet"/>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
          integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e1807ed9b8.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.3/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
</head>

<body>
<header>
    {% include 'navbar.html' %}
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/navbar.html
{% load static %}

<style>
    .nav-wrap {
        background: #2a3954;
        height: 70px;
        line-height: 70px;
        min-width: 884px;
    }

    .nav-wrap .logo {
        float: left;
        margin-left: 30px;
    }

    .nav-wrap .user {
        float: right;
        margin-right: 30px;
    }

    .nav-wrap .logo img {
        width: 150px;
        height: 55px;
    }

    .nav-wrap .logo img:last-child {
        display: none;
    }

    .nav-wrap .logo:hover img:first-child {
        display: none;
    }

    .nav-wrap .logo:hover img:last-child {
        display: inline-block;
    }

    .nav-wrap .menu-bar {
        float: left;
    }

    .nav-wrap .menu {
        float: left;
        list-style: none;
    }

    .nav-wrap .menubtn {
        color: #ffffff;
        padding: 0 13px;
        font-size: 18px;
        font-weight: 600;
        letter-spacing: -0.035em;
        text-decoration-line: none;
        display: list-item;
    }

    .nav-wrap .menu:hover {
        background: #0086d1;
    }

    .nav-wrap .menu:hover .submenu {
        display: inline-block;
        position: absolute;
    }

    .nav-wrap .submenu {
        background: #0086d1;
        display: none;
        padding-inline-start: 0;
        width: 100%;
    }


    .nav-wrap .submenu .menubtn:hover {
        text-decoration-line: underline;
        color: #2a3954;
    }

</style>


<nav class="nav-wrap">
    <a class="logo" href="/">
        <img src="{% static 'img/logo_off.svg' %}">
        <img src="{% static 'img/logo_on.svg' %}">
    </a>
    <ul class="menu-bar">
        <li class="menu">
            <a class="menubtn" href="{% url 'B2C:order' %}">주문 관리</a>
            <ul class="submenu">
                <li class="menu">
                    <a class="menubtn" href="{% url 'B2C:orderlist' %}">주문 조회</a>
                </li>
                <li class="menu">
                    <a class="menubtn" href="">배송일지정 주문</a>
                </li>
            </ul>
        </li>
        <li class="menu">
            <a class="menubtn" href="{% url 'B2C:workorder' %}">작업지시 관리</a>
            <ul class="submenu">
                <li class="menu">
                    <a class="menubtn" href="">작업지시(예정)</a>
                </li>
                <li class="menu">
                    <a class="menubtn" href="">작업지시(확정)</a>
                </li>
            </ul>
        </li>
        <li class="menu">
            <a class="menubtn" href="{% url 'B2C:release' %}">출고리스트</a>
        </li>
        <li class="menu">
            <a class="menubtn" href="{% url 'B2C:salesreport' %}">매체별 일별 매출</a>
        </li>
    </ul>
    {% if user.is_authenticated %}
        <a class="user" href="{% url 'common:logout' %}">{{ user.username }}
            (로그아웃)</a>
    {% else %}
        <a class="user" href="{% url 'common:login' %}">로그인</a>
    {% endif %}
</nav>